pipeline {
 	agent { label 'hostgvt' }
tools {
        jdk 'JDK8gvtlocal'
        maven 'linuxhostmaven'
      }
environment {
        JOB_ANSIBLE_TOOL = "Ansible-gvt"
 }
  
stages {
      
        stage('Get ansible tool PATH') {
            steps {
                script {
                    ansibleHome = tool name: "${env.JOB_ANSIBLE_TOOL}"
 }
            }
        }




	stage('Source') { 
     		 steps {

	checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'ansibleworkspace']], submoduleCfg: [], userRemoteConfigs: [[name: 'Playbook', url: 'https://github.com/happytripgit/deploy.git']]]) 
 

}
    				}
	
     	stage('Compile') { 
          
	        steps{
		    
     	 	  sh 'java -version'
      		  sh 'mvn -version'
dir("happy-trip")
    	{
        sh 'mvn clean package'
      }
 
	
			}
	 
  			 	 }

	
	stage('SonarScan and notify by email') {

        	steps{
dir("happy-trip")
    	{
		        withSonarQubeEnv(installationName: 'SonarQube'){
              		  sh 'mvn sonar:sonar'
		    
          			  }
}
       			 		}
   						 }

     
	 stage('Nexus Artifact Publisher'){
		steps{
	
nexusPublisher nexusInstanceId: 'nexus-123', nexusRepositoryId: 'releases', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: 'war', filePath: 'happy-trip/target/prabhav-1.war']], mavenCoordinate: [artifactId: 'prabhav-1', groupId: 'nexus.happytrip', packaging: 'war', version: '${BUILD_NUMBER}']]]
			}
					}

	stage ('Approval'){
			agent none
            steps{

emailext body: 'Approve build $BUILD_NUMBER of $PROJECT_NAME for test deployment.', subject: 'Test Approval', to: 'pratdeus@gmail.com'

              script {
                 approved = input message: 'Release to test?', ok: 'Yes', submitter: 'pm'
 	   	if (approved) {
    		withCredentials([usernamePassword(credentialsId: 'privilegedCreds', usernameVariable: 'USER', passwordVariable: 'PASS')]) 	
			{		echo "Approved"
    					        		}
    				}
    		      }
                }
                          }

stage('Check Ansible Version') {
            steps {
                sh "${ansibleHome}/ansible --version"
 sh "${ansibleHome}/ansible-playbook --version"
 }
        }
	
  	}

	post{
		

		changed{

emailext attachLog: true, body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

Check console output at $BUILD_URL to view the results of the build.''', compressLog: true, subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!', to: 'pratdeus@gmail.com'
		}

		success{ 

ansiblePlaybook become: true, colorized: true, credentialsId: '0c540f01-a70b-482d-a251-79bf54a02ea7', extras: '--extra-vars \'{"build_number":"${BUILD_NUMBER}"}\'', installation: 'Ansible-gvt', inventory: 'ansibleworkspace/inventories/dev.ini', playbook: 'ansibleworkspace/playbooks/test_environment.yml'

emailext body: 'Approve build $BUILD_NUMBER of $PROJECT_NAME for production deployment.', subject: 'Production Approval', to: 'pratdeus@gmail.com'

              script {
                 approved = input message: 'Release to production?', ok: 'Yes', submitter: 'pm'
 	   	if (approved) {
    		withCredentials([usernamePassword(credentialsId: 'privilegedCreds', usernameVariable: 'USER', passwordVariable: 'PASS')]) 	
			{		echo "Approved" }
				}
}
ansiblePlaybook become: true, colorized: true, disableHostKeyChecking: true, credentialsId: '0c540f01-a70b-482d-a251-79bf54a02ea7', extras: '--extra-vars \'{"build_number":"${BUILD_NUMBER}"}\'', installation: 'Ansible-gvt', inventory: 'ansibleworkspace/inventories/dev.ini', playbook: 'ansibleworkspace/playbooks/production_environment.yml'
    				
    		      
            
		    chuckNorris()
		}


}
		

	
	}
	

