---
- name: installing system dependencies
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ lookup('list', dependencies) }}"

- name: Continuing installation
  include: "docker_key.yml"
